### ISSUE TITLE
Change Event is not triggered on native select

### ISSUE THREAD

**Issue by srikrishnacj** [hardskilled/bootstrap-hardskilled-extend-select#11]
When i change option on bootstrap select that does not trigger change event native select. but changing option directly on native select is triggering change event.

I am using following versions:
    "bootstrap": "4.0.0-beta.2",
    "bootstrap-hardskilled-extend-select": "^1.0.6",

To solve this i have add this line in select.js
        $(option).trigger("change");
below this line
        $(this).toggleClass(options.activeClass);

**Comment by hinex** [comment]
Good point, I fix it today.

**Comment by hinex** [comment]
Fixed on 1.1.0 version

**Comment by srikrishnacj** [comment]
Great!
