### ISSUE TITLE
How to use this inside an input-group

### ISSUE THREAD

**Issue by slidenerd** [hardskilled/bootstrap-hardskilled-extend-select#12]
Would be super great if you can add an example of using this inside an input group in the docs. Thank you for this lib!

**Comment by hinex** [comment]
I'll add it to the next version, thanks!

**Comment by slidenerd** [comment]
The reason I opened this issue is that it doesnt work. If you try placing a select inside an input group, 2 dropdowns appear beside each other

```
    <div class="input-group">
        <input type="text" class="form-control" aria-label="Text input with dropdown button">
        <select id="basic-live" class="form-control" data-live-search="true">
            <option>Rabbit</option>
            <option selected>Cat</option>
            <option class="get-class" disabled>Owl</option>
            <optgroup label="Insects">
                <option>Spider</option>
                <option>Worm</option>
                <option>Fly</option>
            </optgroup>
        </select>
    </div>
```

  
![image 1](https://user-images.githubusercontent.com/5139030/34672276-d9ffe398-f4a3-11e7-9341-6856ac14228b.png)

**Comment by hinex** [comment]
Fixed on 1.1.1 version, check documentation please :)

https://hardskilled.github.io/bootstrap-hardskilled-extend-select/docs/

**Comment by slidenerd** [comment]
![test](https://user-images.githubusercontent.com/5139030/34903568-2d7d4e0c-f85a-11e7-98b2-c89e7038450d.gif)

Its not opening on the latest version of chrome and firefox, any ideas :) thanks for the update.

**Comment by hinex** [comment]
Added fix to the new version, but the CDN has not been updated yet, check it later :)

Thanks!
