### ISSUE TITLE
Custom "Nothing to Show" text?

### ISSUE THREAD

**Issue by DavidAll-n** [hardskilled/bootstrap-hardskilled-extend-select#24]
Any chance of adding the option to specify custom "Nothing to Show" text? It would be nice to be able to change this text to fit the content of the select ("No Bike Selected" for instance).

**Comment by hinex** [comment]
Good point. I will add it soon.

**Comment by hinex** [comment]
Added new attributes at 1.2.0 version: `data-not-selected` and `data-empty`
CDN will be updated soon. Thanks!
