### ISSUE TITLE
Generated dropdown is not populated - Bootstrap v4.0.0-beta

### ISSUE THREAD

**Issue by 0dp** [hardskilled/bootstrap-hardskilled-extend-select#9]
After initializing the basic example with live search, this is the markup that is generated.
The first part is the markup that I inserted as per documentation. The second block is the part generated by the plugin.

As you can see it is empty, only populated by the selected item from the first block. Furthermore options in the dropdown is not being generated after opening as expected.

Currently on Bootstrap v4.0.0-beta

```
<select id="basic-live" class="form-control select-extend" data-live-search="true">
    <option data-index="0">Rabbit</option>
    <option selected="" data-index="1">Cat</option>
    <option class="get-class" disabled="" data-index="2">Owl</option>
    <optgroup label="Insects">
        <option data-index="3">Spider</option>
        <option data-index="4">Worm</option>
        <option data-index="5">Fly</option>
    </optgroup>
</select>

<div class="dropdown select-extended-element">
    <button class="btn dropdown-toggle btn-secondary" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cat</button>
    <div class="dropdown-menu">
        <div class="alert alert-danger select-extend-alert" role="alert"></div>
    </div>
</div>
```

**Comment by hinex** [comment]
The first element that was generated with selected options in button. The options in the dropdown will be generated after opening. This is done so as not to put extra garbage into the layout. If you want to listen to changes, do it on your `<select>`. After changes into dropdown, plugin update options.
 
I'm thinking of adding native methods to more easily track changes in the next version

**Comment by hinex** [comment]
If you have any suggestions or comments on using the plug-in. Let me know here or create a new Issue. Thanks!

**Comment by 0dp** [comment]
Then I should extend my report to include that the options in the dropdown is not being generated after opening.

**Comment by hinex** [comment]
Ok, I'll look at v4.0.0-beta a bit later

**Comment by hinex** [comment]
Hm... I tested:
https://jsfiddle.net/romanhinex/0rt61ey2/

But it worked normally.

Can you show me your code? 
Also, can you check the console for errors?

**Comment by 0dp** [comment]
I just tested your fiddle with the jQuery version i currently use and it works perfect.
I have no console errors and used the example code from the documentation. I will have to look into my setup and see what is creating the conflict. For now I would consider this as resolved.

**Comment by hinex** [comment]
Excellent! Let me know if something changes
